version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build-front:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: install UI dependencies
          command: |
            npm run frontend:install
      - run:
          name: build UI
          command: |
            npm run frontend:build
  build-back:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - run:
          name: install backend dependencies
          command: |
            npm run backend:install
      - run:
          name: build backend
          command: |
            npm run backend:build
workflows:
  udagram:
    jobs:
      # build
      - build-front
      - build-back
